
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end

target 'BuchaSwift_Example' do
    platform :ios, '9.0'
    use_frameworks!

  pod 'BuchaSwift', :path => '../'

end

target 'BuchaSwift_Mac_Example' do
    platform :osx, '10.11'
    use_frameworks!
    pod 'BuchaSwift', :path => '../'
    
end
