use_frameworks!

target 'BuchaSwift_Example' do
  pod 'BuchaSwift', :path => '../'

  target 'BuchaSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
